version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: meyadleyad-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: meyadleyad
      POSTGRES_USER: meyaduser
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./server
    container_name: meyadleyad-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://meyaduser:strongpassword@postgres:5432/meyadleyad
      PORT: 3000
      JWT_SECRET: 86a8e36f0244448bf7c844f96319d5ac8abc3abba9117831936fd4728dcb2785
      JWT_REFRESH_SECRET: feb2bcdecb403a7d313ef20ec4a4d303d31b768c59714e2768fdd18a33171ce1a02c694fef4262613d39c7ddbeba9dd00ecbf0f4041c8658c330c6101a13e584
      SMTP_ENABLED: "false"
      APP_URL: https://amakom.co.il
    env_file: 
      - .env
    volumes:
      - ./data/uploads:/app/uploads
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_GOOGLE_MAPS_API_KEY: AIzaSyCoFMKjWsfVJJpmyoY45kDEeM_pd7xp1As
    container_name: meyadleyad-frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./data/uploads:/usr/share/nginx/html/uploads

volumes:
  postgres_data:

networks:
  app-network:
